### PR TITLE
Update workflow

### PR DESCRIPTION
**Pull request by jjw24**
Updates and enhancements to workflow

### CODE REVIEW

**Comment by HorridModz** [comment]
Thank you so much! It was interesting to read through what you did. Seeing these fixes helps me better understand, though it's still sorcery to me 😆.
I noticed you updated the version to 2.0.1. Shouldn't it say as 2.0.0 since no changes to the actual plugin were made? Regardless, it's a minor semantic and I'm sure you know what you're doing, so I'll trust you on it.

Merging! And adding credit to you in the README as well :)

**Comment by jjw24** [comment]
So the way this workflow works is that it will only publish a release when the version in your main repo is different to the version released. So if we don't change it to 2.0.1 it won't publish a new release because you already have 2.0.0.

**Comment by HorridModz** [comment]
> So the way this workflow works is that it will only publish a release when the version in your main repo is different to the version released. So if we don't change it to 2.0.1 it won't publish a new release because you already have 2.0.0.

Makes sense, but why is a new release needed? Again, if no plugin changes have been made, why can't the plugin's release stay the same?

**Comment by jjw24** [comment]
Mainly because your current releases are manually uploaded, this does not guarantee to the user that what they have downloaded from the repo is what the source code represents. If we use workflow, the release is built directly from the source code here rather than compiled locally and uploaded manually by plugin dev.

**Pull request merged**
